# Site
name: ":: JP Coba Bantu ::"
title: ":: JP Coba Bantu ::"
description: "Keisengan JP menulis tutorial Bahasa Indonesia."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics:
disqus: ' jp-coba-bantu'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Jan Peter Alexander
    display_name: JP
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    web: https://jpmrblood.blogspot.com
    twitter: https://twitter.com/jpmrblood
    description: "Former Programmer with Attitudes -- Quora, 2018."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
